# Generated by Django 5.0.6 on 2024-07-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.chemical')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.formula')),
            ],
        ),
        migrations.AddField(
            model_name='formula',
            name='chemicals',
            field=models.ManyToManyField(through='inventory.FormulaChemical', to='inventory.chemical'),
        ),
    ]
